### PR TITLE
.NET Framework 4.6 & Uno.CodeGen → .NET Core 2.2 & Equals.Fody

### PR DESCRIPTION
**Pull request by dahlia**
This patch replaces Uno.CodeGen, a barrier to adopting .NET Core, with [Equals.Fody], and makes the build process depends on `dotnet` CLI instead of `msbuild`.  (Of course, `msbuild` also still works.)

Pros of .NET Core are:

 -  Behaviors across platforms are more consistent than .NET Framework v. Mono.
 -  Both tests (`Libplanet.Tests` & `Libplanet.Stun.Tests`) can be run at a time on CLI (`dotnet test`).
 -  Tests can be `--filter`ed on CLI as well (whereas xunit.runner.msbuild is only able to run the whole tests.)

Pros of Equals.Fody:

 -  As it rewrites code at IL level, types don't have to be `partial`.
     -  So it's entirely free from the bug #82 without any tricks.
     -  We don't need to add lines of preprocessor directives to suppress warnings.
 -  Works with .NET Framework, Mono, and .NET Core.

Also note that there are some limitations on Equals.Fody when it's compared to Uno.CodeGen:

 -  It doesn't work with generic `struct`s (and generic `class`es?  Not sure).  See `HashDigest<T>` as well; its equality methods are written by hand.
 -  Fields to compare are opt-in by default and can be opt-out by annotating `[IgnoreDuringEquals]` attribute.  This leads types with one identity property and other many properties to look dirty.  See `Block<T>`for example; its properties all have an `[IgnoreDuringEquals]` attribute except for the `Hash` property.
 -  Apparently `operator ==` and `operator !=` are not generated.

[Equals.Fody]: https://github.com/Fody/Equals

### CODE REVIEW

File: CHANGES.md [hunk 1]
```diff
@@ -31,6 +31,10 @@ To be released.
     [[#204]], [[#206]]
  -  Added `BlockDownloadState` class to represent a block downloading state.
     [[#204]], [[#206]]
+ -  Removed `KeyEquals()` methods from all classes and structs.
+ -  `Swarm` class now does not `IEquatable<Swarm>` anymore and
```
Comment (earlbread) [inline CHANGES.md]:
```suggestion
 -  `Swarm` class now does not implement `IEquatable<Swarm>` anymore and
```

**Comment by carldebilly** [comment]
@dahlia `Uno.Code` now works well with dotnet core 3.0.
